openapi: 3.0.0
servers:
  - description: "SwaggerHub API Auto Mocking"
    url: https://virtserver.swaggerhub.com/VNGRealisatie/api/bg_imwoz_koz/v1
  - description: "Referentie-implementatie"
    url: https://www.voorbeeldgemeente.nl/api/bg_imwoz_koz/v1
info:
  title: BG IMWOZ KOZ
  description: ""
  version: "1.0.0"
  x-imvertor-generator-version: "1.65.4"
  x-yamlCompiler-stylesheets-version: "20220110"
  contact:
    url: https://github.com/VNG-Realisatie/IMWOZ-bevragingen
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
paths:
  /kadastraleonroerendezaken:
    get:
      operationId: getkadastraleonroerendezaken
      description: "<body><p>Het bericht dat de JSON/REST API voor het ophalen van een collectie kadstraleonroerendezaken retourneert.</p></body>"
      parameters:
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/parameters.yaml#/acceptCrs"
        - in: query
          name: kadastraleIdentificatie
          description: ""
          required: true
          schema:
            type: string
            pattern: NL\.IMKAD\.KadastraalObject\.[1-9][0-9]{0,14}(\.[0-9]+)?
        - in: query
          name: peiltijdstipMaterieel
          description: ""
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: "Zoekactie geslaagd"
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/warning"
            X-Pagination-Page:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/X_Pagination_Page"
            X-Pagination-Limit:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/X_Pagination_Limit"
            X-Rate-Limit-Limit:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/X_Rate_Limit_Limit"
            X-Rate-Limit-Remaining:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/X_Rate_Limit_Remaining"
            X-Rate-Limit-Reset:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/X_Rate_Limit_Reset"
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/KadastraleOnroerendeZaakHalCollectie'
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/403"
        '406':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/406"
        '409':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/409"
        '410':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/410"
        '412':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/412"
        '415':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/415"
        '429':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/429"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/500"
        '501':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/501"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/503"
        'default':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/default"
      tags:
      - Kadastraleonroerendezaken (KOZ)
  /kadastraleonroerendezaken/{kadastraleidentificatie}:
    get:
      operationId: getkadastraleonroerendezaak
      description: "<body><p>Het bericht dat de JSON/REST API voor het ophalen gegevens van een kadstraleonroerendezaak retourneert.</p></body>"
      parameters:
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/parameters.yaml#/acceptCrs"
        - in: path
          name: kadastraleidentificatie
          description: ""
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Zoekactie geslaagd"
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/warning"
            X-Rate-Limit-Limit:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/X_Rate_Limit_Limit"
            X-Rate-Limit-Remaining:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/X_Rate_Limit_Remaining"
            X-Rate-Limit-Reset:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/X_Rate_Limit_Reset"
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/KadastraleOnroerendeZaakHal'
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/403"
        '404':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/404"
        '406':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/406"
        '409':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/409"
        '410':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/410"
        '412':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/412"
        '415':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/415"
        '429':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/429"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/500"
        '501':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/501"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/503"
        'default':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/default"
      tags:
      - Kadastraleonroerendezaken (KOZ)
components:
  schemas:
    KadastraleOnroerendeZaakHalCollectie:
      type: object
      properties:
        _links:
          $ref: https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/schemas/HalPaginationLinks
        _embedded:
          type: object
          properties:
            kadastraleOnroerendeZaken:
              type: array
              items:
                $ref: '#/components/schemas/KadastraleOnroerendeZaakHal'
    KadastraleOnroerendeZaakHal:
      allOf:
        - $ref: '#/components/schemas/KadastraleOnroerendeZaak'
        - type: object
          properties:
            _links:
              $ref: '#/components/schemas/KadastraleOnroerendeZaak_links'
    KadastraleOnroerendeZaak:
      type: object
      description: <body><p>Kadastrale onroerende zaak komt in de actualiteit in twee gedaanten voor, namelijk als kadastraal perceel of als kadastraal appartement. De attributen begrenzingPerceel en oppervlakte komen alleen voor bij kadastraal perceel. In de historische gegevens van de Basisregistratie WOZ (beëindigde bevatKadastraleObjecten relaties) komen daarnaast ook nog kadastrale deelpercelen voor. De kadastraleIdentificatie moet ook een unieke identificatie geven voor historische kadastrale onroerende zaken. In de Basisregistratie WOZ liggen ook relaties vast naar historische kadastrale onroerende zaken die na 1 januari 2009 zijn beëindigd. Dit informatiemodel gaat ervan uit dat ook voor deze historische kadastrale zaken een kadastraleIdentificatie beschikbaar is. Dit is nog niet door het Kadaster bevestigd.</p></body>
      required:
        - einddatumObject
        - ingangsdatumObject
        - kadastraleAanduiding
        - kadastraleIdentificatie
        - oppervlakte
      properties:
        begrenzingPerceel:
          $ref: https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/geojson.yaml#/Polygon
        einddatumObject:
          $ref: '#/components/schemas/DatumMogelijkOnvolledig'
        inOnderzoek:
          type: array
          items:
            $ref: '#/components/schemas/InOnderzoekKOZ'
        ingangsdatumObject:
          $ref: '#/components/schemas/DatumMogelijkOnvolledig'
        kadastraleAanduiding:
          $ref: '#/components/schemas/KadastraleAanduiding'
        kadastraleIdentificatie:
          type: string
          pattern: NL\.IMKAD\.KadastraalObject\.[1-9][0-9]{0,14}(\.[0-9]+)?
          title: kadastraleIdentificatie
          description: ''
          minLength: 1
        koopsom:
          $ref: '#/components/schemas/Koopsom'
        oppervlakte:
          type: number
          title: oppervlakte
          description: <body><p>Deze attribuutsoort heeft alleen een waarde als het appartementsrechtVolgnummer geen waarde heeft.</p></body>
        tijdstipRegistratie:
          type: string
          title: tijdstipRegistratie
          description: ''
          format: date-time
    KadastraleOnroerendeZaak_links:
      type: object
      properties:
        self:
          $ref: https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/schemas/HalLink
    Bedrag:
      type: object
      description: ''
      required:
        - bedrag
        - valuta
      properties:
        bedrag:
          type: number
          title: bedrag
          description: ''
        valuta:
          allOf:
            - $ref: '#/components/schemas/Valuta'
            - title: valuta
              description: ''
    DatumMogelijkOnvolledig:
      type: object
      description: ''
      required:
        - date
        - jaar
        - jaarMaand
      properties:
        date:
          type: string
          title: Date
          description: ''
          format: date
        jaar:
          $ref: '#/components/schemas/GYear'
        jaarMaand:
          $ref: '#/components/schemas/GYearMonth'
    KadastraleAanduiding:
      type: object
      description: ''
      required:
        - kadastraleGemeente
        - perceelnummer
        - sectie
      properties:
        appartementsrechtVolgnummer:
          type: integer
          title: appartementsrechtVolgnummer
          description: ''
        deelperceelNummer:
          type: integer
          title: deelperceelNummer
          description: ''
        kadastraleGemeente:
          allOf:
            - $ref: '#/components/schemas/KadastraleGemeente'
            - title: kadastraleGemeente
              description: ''
        perceelnummer:
          type: integer
          title: perceelnummer
          description: ''
        sectie:
          type: string
          title: sectie
          description: ''
          pattern: ^[A-Z]{1,2}$
          maxLength: 2
    KadastraleGemeente:
      type: object
      description: ''
      required:
        - code
        - ingangsdatum
        - kadastraleGemeente
      properties:
        code:
          type: string
          title: code
          description: ''
          minLength: 1
        einddatum:
          type: string
          title: einddatum
          description: ''
          format: date
        ingangsdatum:
          type: string
          title: ingangsdatum
          description: ''
          format: date
        kadastraleGemeente:
          type: string
          title: kadastraleGemeente
          description: ''
          minLength: 1
    Koopsom:
      type: object
      description: ''
      required:
        - bedrag
        - indicatieMeerObjecten
        - transactiedatum
      properties:
        bedrag:
          $ref: '#/components/schemas/Bedrag'
        indicatieMeerObjecten:
          type: boolean
          title: indicatieMeerObjecten
          description: ''
        transactiedatum:
          type: string
          title: transactiedatum
          description: ''
          format: date
    Valuta:
      type: object
      description: ''
      required:
        - code
        - ingangsdatum
        - waarde
      properties:
        code:
          type: string
          title: code
          description: ''
          minLength: 1
        einddatum:
          type: string
          title: einddatum
          description: ''
          format: date
        ingangsdatum:
          type: string
          title: ingangsdatum
          description: ''
          format: date
        waarde:
          type: string
          title: waarde
          description: ''
          minLength: 1
    InOnderzoekKOZ:
      type: string
      description: ''
      enum:
        - oppervlakte
        - kadastraleAanduiding
        - begrenzingPerceel
    GYear:
      type: integer
      description: ''
      format: date_fullyear
      pattern: ^[1-2]{1}[0-9]{3}$
    GYearMonth:
      type: integer
      description: ''
      format: date_fullyear
      pattern: ^[1-2]{1}[0-9]{3}$
