
baseurl: "/IMWOZ-bevragingen"
apiname: "IMWOZ-bevragingen"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld.
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt ge√∂pend.
nav:
  - title: IMWOZ-bevragingen
    subnav:
      - title: Main
        path: /
  - title: Specificaties v. 1.0.0
    subnav:
#      - title: Getting started
#        path: /getting-started
#      - title: User stories
#        url: https://vng-realisatie.github.io/IMWOZ-bevragingen/user-stories-prod
#        https://github.com/VNG-Realisatie/IMWOZ-bevragingen/issues?q=is%3Aissue+label%3A%22user+story%22
#        path: /user-stories
      - title: Aanslagregels (swagger-ui)
        path: /ASL-swagger-ui
      - title: Aanslagregels (redoc)
        path: /ASL-redoc
      - title: Biljetten (swagger-ui)
        path: /BLJ-swagger-ui
      - title: Biljetten (redoc)
        path: /BLJ-redoc
      - title: BAG-objecten (swagger-ui)
        path: /BAG-swagger-ui
      - title: BAG-objecten (redoc)
        path: /BAG-redoc
      - title: Bezwaren (swagger-ui)
        path: /BZW-swagger-ui
      - title: Bezwaren (redoc)
        path: /BZW-redoc
      - title: Controleobjectkenmerken (swagger-ui)
        path: /CTL-swagger-ui
      - title: Controleobjectkenmerken (redoc)
        path: /CTL-redoc
      - title: Erfpacht (swagger-ui)
        path: /Erfpacht-swagger-ui
      - title: Erfpacht (redoc)
        path: /Erfpacht-redoc
      - title: Kadastraal Onroerende Zaken (swagger-ui)
        path: /KOZ-swagger-ui
      - title: Kadastraal Onroerende Zaken (redoc)
        path: /KOZ-redoc
      - title: Personen (swagger-ui)
        path: /PRS-swagger-ui
      - title: Personen (redoc)
        path: /PRS-redoc
      - title: Resultaten Marktanalyse (swagger-ui)
        path: /RMA-swagger-ui
      - title: Resultaten Marktanalyse (redoc)
        path: /RMA-redoc
#  - title: Specificaties v. 1.0.0-rc2 (In Ontwikkeling)
#    subnav:
#      - title: Getting started
#        path: /getting-started
#      - title: User stories
#        url: https://vng-realisatie.github.io/IMWOZ-bevragingen/user-stories-prod
#        https://github.com/VNG-Realisatie/IMWOZ-bevragingen/issues?q=is%3Aissue+label%3A%22user+story%22
#        path: /user-stories
#      - title: Bevragingen API (swagger-ui)
#        path: /swagger-ui-io
#      - title: Bevragingen API (redoc)
#        path: /redoc-io


plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: VNG-Realisatie/jekyll-theme-vng-realisatie

github: VNG-Realisatie/IMWOZ-bevragingen

theme: jekyll-theme-time-machine

project_name: /IMWOZ-bevragingen

standard_family: Waarderingskamer
